/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b28c3306ba35ef48691a48b14e46ac28)
interface __BaseEnv_Env {
	DB: D1Database;
	REQUEST_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
